/*  EBIND:  Initial default key to function bindings for
            MicroEMACS 3.7
*/

/*
 * Command table.
 * This table  is *roughly* in ASCII order, left to right across the
 * characters of the command. This expains the funny location of the
 * control-X commands.
 */
KEYTAB keytab[NBINDS] =
{
    { CTRL | 'A', backword },
    { CTRL | 'B', gotoeol },
    { CTRL | 'C', forwpage },
    { CTRL | 'D', forwchar },
    { CTRL | 'E', backline },
    { CTRL | 'F', forwword },
    { CTRL | 'G', ctrlg },
    { CTRL | 'H', backdel },
    { CTRL | 'I', tab },
    { CTRL | 'J', indent },
    { CTRL | 'K', killtext },
    { CTRL | 'L', refresh },
    { CTRL | 'M', newline },
    { CTRL | 'N', forwline },
    { CTRL | 'O', toggleover },
    { CTRL | 'P', backline },
    { CTRL | 'Q', gotobol },
    { CTRL | 'R', backpage },
    { CTRL | 'S', backchar },
    { CTRL | 'T', twiddle },
    { CTRL | 'V', quote },
    { CTRL | 'W', killregion },
    { CTRL | 'X', forwline },
    { CTRL | 'Y', killline },
    { CTRL | 'Z', backpage },
    { CTRL | ']', meta },
    { CTRL | '^', qforwsearch },
    { CTRL | '\\', qbacksearch },
    { META | '^', forwsearch },
    { META | '\\', backsearch },
    { META | ' ', setmark },
    { META | '=', showcpos },
    { META | '/', swlinenum },
    { META | '?', help },
    { META | '!', spawn },
    { META | '#', filter },
    { META | '$', pipe },
    { META | '%', spawncli },
    { META | '.', setmark },
    { META | '>', gotoeob },
    { META | '<', gotobob },
    { META | '~', unmark },
    { META | '@', ctlxrlp },
    { META | 'A', nextbuffer },
    { META | 'B', bindtokey },
    { META | 'C', capword },
    { META | 'D', pipe },
    { META | 'E', quickexit },
    { META | 'F', filefind },
    { META | 'G', gotoline },
    { META | 'H', gotoline },
    { META | 'I', openline },
    { META | 'J', gotoline },
    { META | 'K', killbuffer },
    { META | 'L', lowerword },
    { META | 'M', _setmode },
    { META | 'N', delwind },
    { META | 'O', onlywind },
    { META | 'P', splitwind },
    { META | 'Q', quit },
    { META | 'R', fileread },
    { META | 'S', filesave },
    { META | 'T', filename },
    { META | 'U', upperword },
    { META | 'V', viewfile },
    { META | 'W', filewrite },
    { META | 'X', namedcmd },
    { META | 'Y', insfile },
    { META | 'Z', gotoeob },
    { META | '[', enlargewind },
    { META | ']', getfence },
    { META | 0x7F, delbword },
    { META | CTRL | 'B', usebuffer },
    { META | CTRL | 'H', delbword },
    { META | CTRL | 'L', reposition },
    { META | CTRL | 'M', delmode },
    { META | CTRL | 'N', namebuffer },
    { META | CTRL | 'R', qreplace },
    { META | CTRL | 'T', switchtab },
    { META | CTRL | 'V', scrnextdw },
    { META | CTRL | 'Z', scrnextup },
    { SPEC | '0', gotobob },
    { SPEC | '1', gotoeob },
    { SPEC | '2', sreplace },
    { SPEC | '3', forwsearch },
    { SPEC | '4', forwhunt },
    { SPEC | '5', setmark },
    { SPEC | '6', killregion },
    { SPEC | '7', copyregion },
    { SPEC | '8', yank },
    { SPEC | '9', tagjump },
    { SPEC | 'A', enlargewind },
    { SPEC | 'B', shrinkwind },
    { SPEC | 'C', qreplace },
    { SPEC | 'D', backsearch },
    { SPEC | 'E', backhunt },
    { SPEC | 'F', setmark },
    { SPEC | 'G', killregion },
    { SPEC | 'H', copyregion },
    { SPEC | 'I', yank },
    { SPEC | 'J', spawn },
#if ISRCH
    { SPEC | 'R', risearch },
    { SPEC | 'S', fisearch },
    { SPEC | 'r', risearch },
    { SPEC | 's', fisearch },
#endif
    { SPEC | '?', deskey },
    { SPEC | '^', nextwind },
    { SPEC | '_', ctlxe },
    { 0x7F, forwdel },
    { 0, NULL }
};
